"""UI copy and project data (FR/EN) from the prototype."""

COPY = {
    "fr": {
        "name": "Jessica Kuijer",
        "status": "Assistant IA · répond en quelques secondes",
        "greetingLine1": "Bonjour, je suis Jessica",
        "greetingSub": (
            "Développeuse backend devenue product builder orientée IA. "
            "Posez-moi vos questions sur mon parcours, mes compétences et mes projets."
        ),
        "placeholder": "Écrivez votre message…",
        "disclaimer": "Assistant IA · réponses générées par OpenAI à partir du profil et du parcours réels de Jessica Kuijer",
        "reset": "Nouvelle conversation",
        "promptsTitle": "Quelques idées pour démarrer",
        "prompts": [
            "Quel est ton parcours ?",
            "Tes compétences techniques ?",
            "Montre-moi tes projets récents",
            "Es-tu disponible pour un projet ?",
        ],
        "contactBtn": "Me contacter",
        "contactIntro": "Avec plaisir ! Laisse-moi tes coordonnées et je te recontacte très vite. 👇",
        "projectsIntro": "Voici quelques-uns de mes projets récents 👇",
        "contactFormTitle": "Laisse-moi tes coordonnées",
        "fName": "Nom (optionnel)",
        "fEmail": "Email *",
        "fPhone": "Téléphone (optionnel)",
        "fMsg": "Ton projet ou ta demande en quelques mots…",
        "fSubmit": "Envoyer à Jessica",
        "contactErrorEmail": "Merci d'indiquer un email valide.",
        "contactThanks": "Merci ! J'ai bien noté tes coordonnées, je te recontacte très vite. 🙌",
        "contactDoneTitle": "Coordonnées envoyées",
        "contactDonePrefix": "Je te recontacte à ",
        "projects": [
            {
                "mono": "H",
                "tag": "IA",
                "title": "Assistant IA « Her »",
                "desc": "Assistant personnel — routing OpenAI + Claude, mémoire et voix.",
            },
            {
                "mono": "E",
                "tag": "IA",
                "title": "Préparateur d'entretiens",
                "desc": "Simulation d'entretiens avec évaluation IA.",
            },
            {
                "mono": "M",
                "tag": "IA",
                "title": "Music Discovery AI",
                "desc": "Découverte musicale — Spotify + OpenAI + YouTube.",
            },
            {
                "mono": "E",
                "tag": "Produit",
                "title": "Plateforme E-Motion",
                "desc": "Backend, monorepo, paiements Stripe, performance.",
            },
        ],
        "configErrorTitle": "Configuration requise",
        "configErrorBody": (
            "L'assistant IA de Jessica n'est pas encore configuré. "
            "Les clés API doivent être ajoutées aux secrets Streamlit."
        ),
        "configErrorSecrets": "Secrets requis : OPENAI_API_KEY, PUSHOVER_USER, PUSHOVER_TOKEN",
        "configErrorContact": "En attendant, contactez Jessica à jessicakuijer@me.com",
        "langSwitchEn": "🇬🇧 Jessica will now respond in English!",
        "langSwitchFr": "🇫🇷 Jessica répondra maintenant en français!",
    },
    "en": {
        "name": "Jessica Kuijer",
        "status": "AI Assistant · replies in seconds",
        "greetingLine1": "Hi, I'm Jessica",
        "greetingSub": (
            "Backend developer turned AI-focused product builder. "
            "Ask me anything about my background, skills and projects."
        ),
        "placeholder": "Type your message…",
        "disclaimer": "AI Assistant · responses generated by OpenAI from Jessica Kuijer's real profile and background",
        "reset": "New conversation",
        "promptsTitle": "A few ideas to start",
        "prompts": [
            "What's your background?",
            "Your technical skills?",
            "Show me your recent projects",
            "Are you available for a project?",
        ],
        "contactBtn": "Contact me",
        "contactIntro": "With pleasure! Leave me your details and I'll get back to you very soon. 👇",
        "projectsIntro": "Here are a few of my recent projects 👇",
        "contactFormTitle": "Leave me your details",
        "fName": "Name (optional)",
        "fEmail": "Email *",
        "fPhone": "Phone (optional)",
        "fMsg": "Your project or request in a few words…",
        "fSubmit": "Send to Jessica",
        "contactErrorEmail": "Please enter a valid email.",
        "contactThanks": "Thank you! I've noted your details and will get back to you very soon. 🙌",
        "contactDoneTitle": "Details sent",
        "contactDonePrefix": "I'll reach out at ",
        "projects": [
            {
                "mono": "H",
                "tag": "AI",
                "title": 'AI Assistant "Her"',
                "desc": "Personal assistant — OpenAI + Claude routing, memory and voice.",
            },
            {
                "mono": "E",
                "tag": "AI",
                "title": "Interview Coach",
                "desc": "Interview simulation with AI evaluation.",
            },
            {
                "mono": "M",
                "tag": "AI",
                "title": "Music Discovery AI",
                "desc": "Music discovery — Spotify + OpenAI + YouTube.",
            },
            {
                "mono": "E",
                "tag": "Product",
                "title": "E-Motion Platform",
                "desc": "Backend, monorepo, Stripe payments, performance.",
            },
        ],
        "configErrorTitle": "Configuration required",
        "configErrorBody": (
            "Jessica's AI assistant is not configured yet. "
            "API keys must be added to Streamlit secrets."
        ),
        "configErrorSecrets": "Required secrets: OPENAI_API_KEY, PUSHOVER_USER, PUSHOVER_TOKEN",
        "configErrorContact": "Meanwhile, reach Jessica at jessicakuijer@me.com",
        "langSwitchEn": "🇬🇧 Jessica will now respond in English!",
        "langSwitchFr": "🇫🇷 Jessica répondra maintenant en français!",
    },
}

THEME_LABELS = {
    "clair": "Clair",
    "sombre": "Sombre",
    "editorial": "Éditorial",
}


def session_to_ui_lang(session_language: str) -> str:
    return "en" if session_language == "english" else "fr"
